# Azure DevOps Pipeline para Hazelcast Client no MicroK8s
# Pipeline para build e deploy apenas do cliente Hazelcast
pool:
  name: Arm64
  vmImage: 'ubuntu-22.04'

trigger:
  branches:
    include:
      - main

jobs:
- deployment: DeployJob
  displayName: 'Deploy to Kubernetes'
  pool:
    name: Arm64
    vmImage: 'ubuntu-22.04'
  environment: 'microk8s-cluster'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: KubernetesManifest@0
          displayName: Deploy to Kubernetes cluster
          inputs:
            kubernetesServiceConnection: K8SOracleCloud
            namespace:  'hazelcast' 
            action: deploy
            enableKubectlCommand: true
            arguments: --insecure-skip-tls-verify
            manifests: |
              $(Build.SourcesDirectory)/k8s/01-namespace.yaml
              $(Build.SourcesDirectory)/k8s/02-serviceaccount.yaml
              $(Build.SourcesDirectory)/k8s/03-rbac.yaml
              $(Build.SourcesDirectory)/k8s/04-hazelcast-service.yaml
              $(Build.SourcesDirectory)/k8s/05-hazelcast-deployment.yaml
              $(Build.SourcesDirectory)/k8s/06-mc-service.yaml
              $(Build.SourcesDirectory)/k8s/07-mc-deployment.yaml
              $(Build.SourcesDirectory)/k8s/08-ingress.yaml
              $(Build.SourcesDirectory)/k8s/09-certificate.yaml
              $(Build.SourcesDirectory)/k8s/hazelcast-secrets.yaml
            containers: 'hazelcast/hazelcast:5.5'