# Azure DevOps Pipeline para Hazelcast no Kubernetes
trigger:
  branches:
    include:
      - main

pool:
  name: Arm64

jobs:
- deployment: DeployHazelcast
  displayName: 'Deploy Hazelcast to Kubernetes'
  environment: 'microk8s-cluster'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        
        - task: KubernetesManifest@0
          displayName: 'Deploy Hazelcast to Kubernetes'
          inputs:
            action: deploy
            kubernetesServiceConnection: K8SOracleCloud
            namespace: hazelcast
            manifests: |
              $(Build.SourcesDirectory)/k8s/00-all-resources.yaml