apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hazelcast-ingress
  namespace: hazelcast
  labels:
    app: hazelcast-mc
    component: ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hazelcast.archse.eng.br
    secretName: hazelcast-tls
  rules:
  - host: hazelcast.archse.eng.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hazelcast-mc-service
            port:
              number: 8080
