apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast
  namespace: hazelcast
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hazelcast-discovery
  namespace: hazelcast
rules:
- apiGroups: [""]
  resources: ["endpoints", "pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-discovery-binding
  namespace: hazelcast
subjects:
- kind: ServiceAccount
  name: hazelcast
  namespace: hazelcast
roleRef:
  kind: Role
  name: hazelcast-discovery
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
  namespace: hazelcast
  labels:
    app: hazelcast
spec:
  type: ClusterIP
  selector:
    app: hazelcast
  ports:
    - name: hazelcast
      port: 80
      targetPort: 5701
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
  namespace: hazelcast
  labels:
    app: hazelcast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: hazelcast
        image: hazelcast/hazelcast:latest
        ports:
        - containerPort: 5071
          name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hazelcast-ingress
  namespace: hazelcast
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hazelcast.archse.eng.br
    secretName: hazelcast-tls
  rules:
  - host: hazelcast.archse.eng.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hazelcast-mc-service
            port:
              number: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: framework-tls
  namespace: default
spec:
  secretName: hazelcast-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - hazelcast.archse.eng.br