apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hazelcast-tls
  namespace: default
spec:
  secretName: hazelcast-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - hazelcast.archse.eng.br
